# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class DemuxProxy < Formula
  desc "Proxy that takes a single input and then switches it to any one of a number of interfaces"
  homepage "https://github.com/mberwanger/demux-proxy"
  version "0.1.0"
  bottle :unneeded

  if OS.mac? && Hardware::CPU.intel?
    url "https://github.com/mberwanger/demux-proxy/releases/download/v0.1.0/demux-proxy_0.1.0_Darwin_x86_64.tar.gz"
    sha256 "735c1aaca76e6d94b975a00c03cde3ce62f29ade2f18b5799d0546f94704db2a"
  end
  if OS.mac? && Hardware::CPU.arm?
    url "https://github.com/mberwanger/demux-proxy/releases/download/v0.1.0/demux-proxy_0.1.0_Darwin_arm64.tar.gz"
    sha256 "0bae962c77462f81cafda5f20e6ad92288f9b231f66113a1ba1e5bf84b989292"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/mberwanger/demux-proxy/releases/download/v0.1.0/demux-proxy_0.1.0_Linux_x86_64.tar.gz"
    sha256 "9bbd33fe67376bfe194f6d33beb114d128b9c175f12390a0ef8f4583c4b94d93"
  end
  if OS.linux? && Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
    url "https://github.com/mberwanger/demux-proxy/releases/download/v0.1.0/demux-proxy_0.1.0_Linux_armv6.tar.gz"
    sha256 "8dd4afb808f3d0075c1c595b0394a8851526a64ee3b72727eb090802d8077614"
  end
  if OS.linux? && Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/mberwanger/demux-proxy/releases/download/v0.1.0/demux-proxy_0.1.0_Linux_arm64.tar.gz"
    sha256 "61e6c134b64b46a6d3d02655c96ccfa34f03ea4a4354822f7ade24c241786227"
  end

  depends_on "go"

  def install
    bin.install "demux-proxy"
  end

  test do
    system "#{bin}/demux-proxy -v"
  end
end
