# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class DemuxProxy < Formula
  desc "Proxy that takes a single input and then switches it to any one of a number of interfaces"
  homepage "https://github.com/mberwanger/demux-proxy"
  version "0.1.0"
  bottle :unneeded

  if OS.mac? && Hardware::CPU.intel?
    url "https://github.com/mberwanger/demux-proxy/releases/download/v0.1.0/demux-proxy_0.1.0_Darwin_x86_64.tar.gz"
    sha256 "4e9a726e96e9fb5d7cb63679614cb4efec9662aac1767ce0a860fe03b04ff40f"
  end
  if OS.mac? && Hardware::CPU.arm?
    url "https://github.com/mberwanger/demux-proxy/releases/download/v0.1.0/demux-proxy_0.1.0_Darwin_arm64.tar.gz"
    sha256 "ffcf9836b11e8a28cce797993a1bc4b0f33b5d06eb7f2c5b9c6df25625741456"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/mberwanger/demux-proxy/releases/download/v0.1.0/demux-proxy_0.1.0_Linux_x86_64.tar.gz"
    sha256 "73bd3be95ce5c8967b7888ed46c45d5552f5c8998e2b520c0cf7667370845eca"
  end
  if OS.linux? && Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
    url "https://github.com/mberwanger/demux-proxy/releases/download/v0.1.0/demux-proxy_0.1.0_Linux_armv6.tar.gz"
    sha256 "f084c39def2f0d57559c360eb0359fb5c682e63a2a8770a52821940b4222be02"
  end
  if OS.linux? && Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/mberwanger/demux-proxy/releases/download/v0.1.0/demux-proxy_0.1.0_Linux_arm64.tar.gz"
    sha256 "1a083e0be6398a881b90db12299222efc9512f91f9aa8fcbacfdf10e1cc4c2de"
  end

  depends_on "go"

  def install
    bin.install "demux-proxy"
  end

  test do
    system "#{bin}/demux-proxy -v"
  end
end
