# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Updog < Formula
  desc "UpDog enables the management of your DataDog monitors in HCL files"
  homepage "https://github.com/mberwanger/updog"
  version "0.0.1"
  license "MPLv2"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/mberwanger/updog/releases/download/v0.0.1/updog_darwin_x86_64.tar.gz"
      sha256 "694f67b3536d8e83c2f94a60a2906691e562ac76228391109b96f428b29a8658"
    end
    if Hardware::CPU.arm?
      url "https://github.com/mberwanger/updog/releases/download/v0.0.1/updog_darwin_arm64.tar.gz"
      sha256 "df937d02b642faa36b7710cd3fc054f9c18640cb16029942605a17d8dd32eb2d"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/mberwanger/updog/releases/download/v0.0.1/updog_linux_x86_64.tar.gz"
      sha256 "b944948d9ea26c867546df6a4d83ea0d2078d16ba15781860c8fd226c81d277b"
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/mberwanger/updog/releases/download/v0.0.1/updog_linux_armv6.tar.gz"
      sha256 "4df03ed580784e7aa8a1f5527397577056f167c34113d1ee1c33d7407eafdcb4"
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/mberwanger/updog/releases/download/v0.0.1/updog_linux_arm64.tar.gz"
      sha256 "c834ed6f2a88cdcf5d74fd5544fb72d986f385acdb8a303b14d26039ad11e6c5"
    end
  end

  depends_on "go" => :optional
  depends_on "git"

  def install
    bin.install "updog"
    bash_completion.install "completions/updog.bash" => "updog"
    zsh_completion.install "completions/updog.zsh" => "_updog"
    fish_completion.install "completions/updog.fish"
  end

  test do
    system "#{bin}/updog -v"
  end
end
