# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Updog < Formula
  desc "UpDog enables the management of your DataDog monitors in HCL files"
  homepage "https://github.com/mberwanger/updog"
  version "0.0.1"
  license "MPLv2"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/mberwanger/updog/releases/download/v0.0.1/updog_darwin_x86_64.tar.gz"
      sha256 "e4581e93629b093f46d65fbbf5eaddb1e49b4c67854c3274873a284378635a8a"
    end
    if Hardware::CPU.arm?
      url "https://github.com/mberwanger/updog/releases/download/v0.0.1/updog_darwin_arm64.tar.gz"
      sha256 "7c6366c67f33306ab387befe750673659dd6f745df514230d58424eb78b84df8"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/mberwanger/updog/releases/download/v0.0.1/updog_linux_x86_64.tar.gz"
      sha256 "92200c9eaca1bb2e64126f8e9ea6e5ddb7502cae2e4e296e84b6d53700073263"
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/mberwanger/updog/releases/download/v0.0.1/updog_linux_armv6.tar.gz"
      sha256 "6c72bce97c4afa25d43b3c32898505042da97e7dc456cd0d3de31559e6a6e37f"
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/mberwanger/updog/releases/download/v0.0.1/updog_linux_arm64.tar.gz"
      sha256 "218ba7ecd1aa2656a7209b8102cd574a483fc777e95e11482ba62f0fbb8f3740"
    end
  end

  depends_on "go" => :optional
  depends_on "git"

  def install
    bin.install "updog"
    bash_completion.install "completions/updog.bash" => "updog"
    zsh_completion.install "completions/updog.zsh" => "_updog"
    fish_completion.install "completions/updog.fish"
  end

  test do
    system "#{bin}/updog -v"
  end
end
